### ISSUE TITLE
Nice use of datalist

### ISSUE THREAD

**Issue by helenzhou6** [fac-13/endangered-animals#35]
- Nice job guys! 👍
- I love how the arrow on the input box appears on the right hand side only when you have autocomplete results
- You have arrow key functions!! Whaa! We spent ages trying to figure out how to do it and didn't manage to do it
- You used `datalist` in your HTML (which is why I think you get the default stuff above ^)

**Comment by vlbee** [comment]
👍👍👍

**Comment by helenzhou6** [comment]
```
<input list="browsers">

<datalist id="browsers">
  <option value="Internet Explorer">
  <option value="Firefox">
  <option value="Chrome">
  <option value="Opera">
  <option value="Safari">
</datalist>
```
^ Yes it's default dropdown stuff when you use `datalist` and `input` 😱 amazing!

**Comment by helenzhou6** [comment]
Although relate #42 
But still awesome for those not using Safari!
