### ISSUE TITLE
Bug: autocomplete option dissappears when it narrows down to one

### ISSUE THREAD

**Issue by vlbee** [fac-13/endangered-animals#45]
As I type larus I get a bunch of options, but as i continue to type larus canus (only one option "larus c...") the autocomplete suggestion disappears. Would be nice to keep it up so I can finish typing or select it once it narrow down to one option. 

![image](https://user-images.githubusercontent.com/32312712/37825316-3dc947c6-2e87-11e8-80ea-fc07b2a99580.png)

![image](https://user-images.githubusercontent.com/32312712/37825328-482b1e6a-2e87-11e8-9767-b5cb39f4dbac.png)

**Comment by i2xzy** [comment]
relates #36

**Comment by GiuliaTeggi** [comment]
Thank you, we solved the Issue now! ;)
